#Compile with ./tarql -d semicolon /comptes/E134932Q/Documents/M1/Web_Semantique/projet_semantique/build_graphe.sparql > result.ttl

PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX cwmo: 	<http://purl/org/cwmo/>
PREFIX schema: 	<http://schema.org/>

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
	?PersonId a schema:Person;
        schema:repeatFrequency			?StackOverflowVisit;
		dbpedia:duration 				?YearsCoding;
		dbpedia:age 					?Age;
		dbpedia:time 					?WakeTime;
		cwmo:tool 						?IDE;
		schema:gender 					?Gender;
		schema:country 					?Country;
		schema:jobTitle 				?DevType;
		schema:employmentType 			?Employment;
		schema:numberOfEmployees 		?CompanySize;
		schema:openingHours 			?hoursComputer;
		schema:operatingSystem 			?OperatingSystem;
		schema:actionPlatform 			?Platform;
		schema:ComputerLanguage 		?LanguageWorkedWith;
		schema:baseSalary 				?Salary.
	?Salary schema:salaryCurrency 		?CurrencySymbol;
		schema:estimatedSalary 		?ConvertedSalary.
}
FROM <file:dev.csv>
WHERE {
	BIND(URI(?Respondent) AS ?PersonId)
	BIND(URI(xsd:integer(?Salary)) AS ?Salary)
	BIND(xsd:string(?Country) AS ?Country)
	BIND(xsd:string(?Employment) AS ?Employment)
	BIND(xsd:string(?CompanySize) AS ?CompanySize)
	BIND(xsd:string(?DevType) AS ?DevType)
	BIND(xsd:string(?YearsCoding) AS ?YearsCoding)
	BIND(xsd:integer(?ConvertedSalary) AS ?ConvertedSalary)
	BIND(xsd:string(?CurrencySymbol) AS ?CurrencySymbol)
	BIND(xsd:string(?LanguageWorkedWith) AS ?LanguageWorkedWith)
	BIND(xsd:string(?PlatformWorkedWith) AS ?PlatformWorkedWith)
	BIND(xsd:string(?IDE) AS ?IDE)
	BIND(xsd:string(?OperatingSystem) AS ?OperatingSystem)
	BIND(xsd:string(?StackOverflowVisit) AS ?StackOverflowVisit)
	BIND(xsd:string(?WakeTime) AS ?WakeTime)
	BIND(xsd:string(?HoursComputer) AS ?HoursComputer)
	BIND(xsd:string(?Gender) AS ?Gender)
	BIND(xsd:string(?Age) AS ?Age)
}



